---
title: "Comorbidity Indices for Predicting Readmissions"
subtitle: "Machine Learning Approaches"
author: "Anobel Y Odisho, Ruth Etzioni, John L Gore"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    css: floating.css
    toc: true
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  cache = T,
  dev = 'quartz_pdf')
```

```{r packages, cache=F}
# Data Cleaning Packages
library(parallel)   # for parallel processing mclapply
options(mc.cores = detectCores()) # set cores to system max

library(dplyr)      # Data Management
library(tidyr)      # Data Cleaning
library(stringr)    # String manipulation
library(broom)      # Tidy regression results

# Graphics Packages
library(knitr)
library(ggplot2)    # Graphics
library(ggthemes)   # Themes for ggplot
library(plotROC)
library(DT)         # HTML Widget for Data Tables
library(stargazer)  # HTML Tables for regression results

# Specialty/Stats Packages
library(ROCR)       # Performance measures, ROC curves, AUC
library(icd)        # ICD package
library(glmnet)
# library(multidplyr)
# library(lme4)     # Mixed Effects Models
# library(coin)     # Permutation Testing
```

```{r importdata}
# Import data
pt <- readRDS("data/patient/tidy/pt_rml.rds")

# center variables
pt$agyradm_s <- scale(pt$agyradm)

# split data into training and validation cohorts
# Set random seed to reproduce results
set.seed(7)

# Create an index variable which will allow splitting of training/test data without overlap
pt$index <- seq(1:nrow(pt))

# Group by OSHPD_ID, then take a 75% sample for training set
train <- pt %>%
  group_by(cohort) %>%
  sample_frac(size=0.75, replace=F)

# Anything that didnt make it into training set is put into a test set
test <- pt[!(pt$index %in% train$index),]

# Remove index variables
pt <- pt %>% select(-index)
train <- train %>% select(-index)
test <- test %>% select(-index)
```

```{r constants}
# Define colors for charts
c <- list()
c$dblue <- "#506380"
c$teal <- "#18A3AC"
c$blue <- "#178CCB"
c$orange <- "#F48024"

# HCC names
hccnames <- read.csv("data/raw/hcc/hcc_labels.csv", stringsAsFactors = F)

# Calculate counts
counts <- pt %>%
  group_by(cohort) %>%
  summarise(n = n())

# Make a vector of cohort names
# Will use this for functions/operations
cohorts <- counts$cohort

# Number of cohorts (used in functions/for loops)
numcohorts <- length(cohorts)

# create empty list of terms for later use
terms <- list()

########## Regression Formulas
# save formulas for regression models
elixfm <- paste0(grep("elix_", names(pt), value = T), collapse = "+")
elixfm.full <- as.formula(paste("isreadmit30dc ~ agyradm_s + sex + ", elixfm, sep = ""))
elixfm <- as.formula(paste("isreadmit30dc", elixfm, sep = "~"))

cdfm <- paste0(grep("cd_", names(pt), value = T), collapse = "+")
cdfm.full <- as.formula(paste("isreadmit30dc ~ agyradm_s + sex + ", cdfm, sep = ""))
cdfm <- as.formula(paste("isreadmit30dc", cdfm, sep = "~"))

hccfm <- paste0(grep("hcc_", names(pt), value = T), collapse = "+")
hccfm.full <- as.formula(paste("isreadmit30dc ~ agyradm_s + sex + ", hccfm, sep = ""))
hccfm <- as.formula(paste("isreadmit30dc", hccfm, sep = "~"))
```

# Forward Logistic Model Selection

Using AIC for model selection, 15 maximum steps

## Elixhauser
```{r elixForwardLog}
# Create empty data frame to populate with forward logistic results
elixforward <- vector("list", numcohorts)
# fit forward stepwise models for all 4 cohorts
for (i in 1:numcohorts) {
  elixmodeldata <- pt %>% 
    filter(cohort==cohorts[[i]]) %>%
    select(isreadmit30dc, agyradm_s, sex, starts_with("elix_")) %>%
    ungroup()
  glmelixfull = glm(elixfm.full, data=elixmodeldata, family="binomial")
  glmelixempty = glm(isreadmit30dc ~ agyradm_s + sex, data=elixmodeldata, family="binomial")
  elixforward[[i]] <- step(glmelixempty,
                          scope = list(
                            lower = formula(glmelixempty),
                            upper = formula(glmelixfull)),
                          direction = "forward",
                          steps=20,
                          trace=0)
}

# exponentiate results, calculate confidence intervals
# convert results into a data frame, append cohort names
elixforwardres <- vector("list", numcohorts)
for (i in 1:numcohorts) {
  elixforwardres[[i]] <- cbind(
      cohort = cohorts[[i]],
      tidy(elixforward[[i]], exponentiate = T),
      ci = exp(confint(elixforward[[i]]))
  )
  names(elixforwardres[[i]]) <- c("cohort", "term", "OR", "se", "statistic", "pvalue", "ci.low", "ci.high")
  elixforwardres[[i]] <- elixforwardres[[i]] %>% 
    mutate(term = str_replace_all(term, "elix_|TRUE","")) %>%
    select(cohort, term, OR, ci.low, ci.high, pvalue)
}

elixforwardres <- elixforwardres %>%
  rbind_all() %>%
  gather(variable, value, -cohort, -term) %>%
  mutate(value = round(value, digits=4)) %>%
  unite(cohort_var, cohort, variable) %>%
  spread(cohort_var, value)

# export results
write.csv(elixforwardres, file="exports/elixforward.csv")
  
# display table of results from elixforward regression
kable(elixforwardres)
```

## Charlson
```{r cdForwardLog}
# Create empty data frame to populate with forward logistic results
cdforward <- vector("list", numcohorts)
# fit forward stepwise models for all 4 cohorts
for (i in 1:numcohorts) {
  cdmodeldata <- pt %>% 
    filter(cohort==cohorts[[i]]) %>%
    select(isreadmit30dc, agyradm_s, sex, starts_with("cd_")) %>%
    ungroup()
  glmcdfull = glm(cdfm.full, data=cdmodeldata, family="binomial")
  glmcdempty = glm(isreadmit30dc ~ agyradm_s + sex, data=cdmodeldata, family="binomial")
  cdforward[[i]] <- step(glmcdempty,
                          scope = list(
                            lower = formula(glmcdempty),
                            upper = formula(glmcdfull)),
                          direction = "forward",
                          steps=20)
}

# exponentiate results, calculate confidence intervals
# convert results into a data frame, append cohort names
cdforwardres <- vector("list", numcohorts)
for (i in 1:numcohorts) {
  cdforwardres[[i]] <- cbind(
      cohort = cohorts[[i]],
      tidy(cdforward[[i]], exponentiate = T),
      ci = exp(confint(cdforward[[i]]))
  )
  names(cdforwardres[[i]]) <- c("cohort", "term", "OR", "se", "statistic", "pvalue", "ci.low", "ci.high")
  cdforwardres[[i]] <- cdforwardres[[i]] %>% 
    mutate(term = str_replace_all(term, "cd_|TRUE","")) %>%
    select(cohort, term, OR, ci.low, ci.high, pvalue)
}

cdforwardres <- cdforwardres %>%
  rbind_all() %>%
  gather(variable, value, -cohort, -term) %>%
  mutate(value = round(value, digits=4)) %>%
  unite(cohort_var, cohort, variable) %>%
  spread(cohort_var, value)

# export results
write.csv(cdforwardres, file="exports/cdforward.csv")
  
# display table of results from cdforward regression
kable(cdforwardres)
```

## HCC
```{r hccForwardLog}
# Create empty data frame to populate with forward logistic results
hccforward <- vector("list", numcohorts)
# fit forward stepwise models for all 4 cohorts
for (i in 1:numcohorts) {
  hccmodeldata <- pt %>% 
    filter(cohort==cohorts[[i]]) %>%
    select(isreadmit30dc, agyradm_s, sex, starts_with("hcc_")) %>%
    ungroup()
  glmhccfull = glm(hccfm.full, data=hccmodeldata, family="binomial")
  glmhccempty = glm(isreadmit30dc ~ agyradm_s + sex, data=hccmodeldata, family="binomial")
  hccforward[[i]] <- step(glmhccempty,
                          scope = list(
                            lower = formula(glmhccempty),
                            upper = formula(glmhccfull)),
                          direction = "forward",
                          steps=20)
}

# exponentiate results, calculate confidence intervals
# convert results into a data frame, append cohort names
hccforwardres <- vector("list", numcohorts)
for (i in 1:numcohorts) {
  hccforwardres[[i]] <- cbind(
      cohort = cohorts[[i]],
      tidy(hccforward[[i]], exponentiate = T),
      ci = exp(confint(hccforward[[i]]))
  )
  names(hccforwardres[[i]]) <- c("cohort", "term", "OR", "se", "statistic", "pvalue", "ci.low", "ci.high")
  hccforwardres[[i]] <- hccforwardres[[i]] %>% 
    mutate(term = str_replace_all(term, "hcc_|TRUE","")) %>%
    select(cohort, term, OR, ci.low, ci.high, pvalue)
}

hccforwardres <- hccforwardres %>%
  rbind_all() %>%
  gather(variable, value, -cohort, -term) %>%
  mutate(value = round(value, digits=4)) %>%
  unite(cohort_var, cohort, variable) %>%
  spread(cohort_var, value)

# export results
write.csv(hccforwardres, file="exports/hccforward.csv")
  
# display table of results from hccforward regression
kable(hccforwardres)
```

# Lasso Model Selection
## Elixhauser
```{r lassoelix}
# make full dataset for elix
elixmodeldata <- pt %>%
  group_by(cohort) %>% 
  select(isreadmit30dc, agyradm_s, sex, starts_with("elix_"))

# create empty objects to later populate
fullelixl <- list()
fullelixm <- vector("list", numcohorts)

# prepare Matrix objects for Lasso regression
# this creates a list of matrices, one for each cohort
for (i in 1:numcohorts) {
  # convert from DF to list
  fullelixl[[i]] <- elixmodeldata %>% filter(cohort==cohorts[i]) %>% ungroup()
  # convert to model matrix
  fullelixm[[i]]$x <- model.matrix(isreadmit30dc~., fullelixl[[i]][,-1])
  fullelixm[[i]]$y = fullelixl[[i]]$isreadmit30dc
  }
rm(fullelixl)

# create empty objects to later populate
cv.lassoelix <- vector("list", numcohorts)
lasso.coef <- vector("list", numcohorts)

# create a vector for penalty factors
# the goal is to set the penalty factor for two specific variables to zero
# these variables are age and gender. setting penalty factor to zero
# ensures that they stay in all the models

# first create a vector, with length equal to number of variables
# setting all penatly factors to 1 (default0)
# then for the age/sex variables: set the penatly to zero
pfac <- rep(1, length(elixmodeldata)-1)
pfac[c(2:3)] <- 0

# create grid of possible lambdas for cross validated lasso 
# from this, identify the minimum lamda to use when fitting model
grid <- 10^seq(10, -2, length=100)

# run a 10-fold cross-validated lasso model, fora  grid of lambdas
# separate mdoel for each cohort
# then use the minimum lambda (lambda at which the CV error is minimized)
# to estimate coefficients
for (i in 1:numcohorts) {
  # fit CV lasso model
  cv.lassoelix[[i]] <- cv.glmnet(fullelixm[[i]]$x, fullelixm[[i]]$y,
                      family = "binomial",
                      alpha = 1,
                      lambda = grid,
                      nfolds = 10,
                      penalty.factor=pfac)
  lasso.coef[[i]] <- coef(cv.lassoelix[[i]], s = cv.lassoelix[[i]]$lambda.min)
  }

# Assign names to variables to create tables
lasso.coef.names <- lasso.coef[[1]]@Dimnames[[1]]

# convert list of matrices to DFs, add cohort name
# then cominbe into a single DF
lasso.coef <- lapply(lasso.coef, as.data.frame(as.matrix))
lasso.coef <-  mapply(cbind, lasso.coef, "cohort" = cohorts, SIMPLIFY = F)
lasso.coef <- do.call(rbind, lasso.coef)

# remove elix/TRUE from variable names and remove intercept from display table
lasso.coef$elix <- str_replace_all(lasso.coef.names, "elix_|TRUE", "")
lasso.coef <- lasso.coef %>% filter(elix != "(Intercept)")

# convert from long to wide table
lasso.coef <- spread(lasso.coef, cohort, X1)
cat("Elixhauser factors that are not present in any of the models")

# show variables that are not selected in any models
lasso.coef$elix[rowSums(lasso.coef[, -1]) == 0]

# create interactive data table 
lasso.coef.dt <- lasso.coef[rowSums(lasso.coef[,-1]) > 0, ]
kable(lasso.coef.dt, digits=3, row.names = F)
```

## Charlson
```{r lassocd}
# make full dataset for cd
cdmodeldata <- pt %>%
  group_by(cohort) %>% 
  select(isreadmit30dc, agyradm_s, sex, starts_with("cd_"))

# create empty objects to later populate
fullcdl <- list()
fullcdm <- vector("list", numcohorts)

# prepare Matrix objects for Lasso regression
??# this creates a list of matrices, one for each cohort
for (i in 1:numcohorts) {
  # convert from DF to list
  fullcdl[[i]] <- cdmodeldata %>% filter(cohort==cohorts[i]) %>% ungroup()
  # convert to model matrix
  fullcdm[[i]]$x <- model.matrix(isreadmit30dc~., fullcdl[[i]][,-1])
  fullcdm[[i]]$y = fullcdl[[i]]$isreadmit30dc
  }
rm(fullcdl)

# create empty objects to later populate
cv.lassocd <- vector("list", numcohorts)
lasso.coef <- vector("list", numcohorts)

# create a vector for penalty factors
# the goal is to set the penalty factor for two specific variables to zero
# these variables are age and gender. setting penalty factor to zero
# ensures that they stay in all the models

# first create a vector, with length equal to number of variables
# setting all penatly factors to 1 (default0)
# then for the age/sex variables: set the penatly to zero
pfac <- rep(1, length(cdmodeldata)-1)
pfac[c(2:3)] <- 0

# create grid of possible lambdas for cross validated lasso 
# from this, identify the minimum lamda to use when fitting model
grid <- 10^seq(10, -2, length=100)

# run a 10-fold cross-validated lasso model, fora  grid of lambdas
# separate mdoel for each cohort
# then use the minimum lambda (lambda at which the CV error is minimized)
# to estimate coefficients
for (i in 1:numcohorts) {
  # fit CV lasso model
  cv.lassocd[[i]] <- cv.glmnet(fullcdm[[i]]$x, fullcdm[[i]]$y,
                      family = "binomial",
                      alpha = 1,
                      lambda = grid,
                      nfolds = 10,
                      penalty.factor=pfac)
  lasso.coef[[i]] <- coef(cv.lassocd[[i]], s = cv.lassocd[[i]]$lambda.min)
  }

# Assign names to variables to create tables
lasso.coef.names <- lasso.coef[[1]]@Dimnames[[1]]

# convert list of matrices to DFs, add cohort name
# then cominbe into a single DF
lasso.coef <- lapply(lasso.coef, as.data.frame(as.matrix))
lasso.coef <-  mapply(cbind, lasso.coef, "cohort" = cohorts, SIMPLIFY = F)
lasso.coef <- do.call(rbind, lasso.coef)

# remove cd/TRUE from variable names and remove intercept from display table
lasso.coef$cd <- str_replace_all(lasso.coef.names, "cd_|TRUE", "")
lasso.coef <- lasso.coef %>% filter(cd != "(Intercept)")

# convert from long to wide table
lasso.coef <- spread(lasso.coef, cohort, X1)
cat("cdhauser factors that are not present in any of the models")

# show variables that are not selected in any models
lasso.coef$cd[rowSums(lasso.coef[, -1]) == 0]

# create interactive data table 
lasso.coef.dt <- lasso.coef[rowSums(lasso.coef[,-1]) > 0, ]
kable(lasso.coef.dt, digits=3, row.names = F)
```

## HCC
```{r lassoHCC}
# make full dataset for hcc
hccmodeldata <- pt %>%
  group_by(cohort) %>% 
  select(isreadmit30dc, agyradm_s, sex, starts_with("hcc_"))

# create empty objects to later populate
fullhccl <- list()
fullhccm <- vector("list", numcohorts)

# prepare Matrix objects for Lasso regression
# this creates a list of matrices, one for each cohort
for (i in 1:numcohorts) {
  # convert from DF to list
  fullhccl[[i]] <- hccmodeldata %>% filter(cohort==cohorts[i]) %>% ungroup()
  # convert to model matrix
  fullhccm[[i]]$x <- model.matrix(isreadmit30dc~., fullhccl[[i]][,-1])
  fullhccm[[i]]$y = fullhccl[[i]]$isreadmit30dc
  }
rm(fullhccl)

# create empty objects to later populate
cv.lassohcc <- vector("list", numcohorts)
lasso.coef <- vector("list", numcohorts)

# create a vector for penalty factors
# the goal is to set the penalty factor for two specific variables to zero
# these variables are age and gender. setting penalty factor to zero
# ensures that they stay in all the models

# first create a vector, with length equal to number of variables
# setting all penatly factors to 1 (default0)
# then for the age/sex variables: set the penatly to zero
pfac <- rep(1, length(hccmodeldata)-1)
pfac[c(2:3)] <- 0

# create grid of possible lambdas for cross validated lasso 
# from this, identify the minimum lamda to use when fitting model
grid <- 10^seq(10, -2, length=100)

# run a 10-fold cross-validated lasso model, fora  grid of lambdas
# separate mdoel for each cohort
# then use the minimum lambda (lambda at which the CV error is minimized)
# to estimate coefficients
for (i in 1:numcohorts) {
  # fit CV lasso model
  cv.lassohcc[[i]] <- cv.glmnet(fullhccm[[i]]$x, fullhccm[[i]]$y,
                      family = "binomial",
                      alpha = 1,
                      lambda = grid,
                      nfolds = 10,
                      penalty.factor=pfac)
  lasso.coef[[i]] <- coef(cv.lassohcc[[i]], s = cv.lassohcc[[i]]$lambda.min)
  }

# Assign names to variables to create tables
lasso.coef.names <- lasso.coef[[1]]@Dimnames[[1]]

# convert list of matrices to DFs, add cohort name
# then cominbe into a single DF
lasso.coef <- lapply(lasso.coef, as.data.frame(as.matrix))
lasso.coef <-  mapply(cbind, lasso.coef, "cohort" = cohorts, SIMPLIFY = F)
lasso.coef <- do.call(rbind, lasso.coef)

# remove HCC/TRUE from variable names and remove intercept from display table
lasso.coef$hcc <- str_replace_all(lasso.coef.names, "hcc_|TRUE", "")
lasso.coef <- lasso.coef %>% filter(hcc != "(Intercept)")

# convert from long to wide table
lasso.coef <- spread(lasso.coef, cohort, X1)

cat("HCC factors that are not present in any of the models")

# show variables that are not selected in any models
lasso.coef$hcc[rowSums(lasso.coef[, -1]) == 0]

# create interactive data table 
lasso.coef.dt <- lasso.coef[rowSums(lasso.coef[,-1]) > 0, ]
kable(lasso.coef.dt, digits=3, row.names = F)
```
